/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseIcon: typeof import('./src/components/BaseIcon.vue')['default']
    DarkModeSwitch: typeof import('./src/components/DarkModeSwitch.vue')['default']
    EssentialLink: typeof import('./src/components/EssentialLink.vue')['default']
    ExampleComponent: typeof import('./src/components/ExampleComponent.vue')['default']
    HeadAndMeta: typeof import('./src/components/HeadAndMeta.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
